import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NoiseBackground from "@/components/NoiseBackground";
import { Navbar } from "@/layouts/Navbar";
import MainLayout from "@/layouts/MainLayout";
import Footer from "@/layouts/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-[#151312]`}
      >
        <NoiseBackground className="relative z-10 container pt-6">
          <Navbar />
          <MainLayout>{children}</MainLayout>
          <Footer />
        </NoiseBackground>
      </body>
    </html>
  );
}
