import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import NoiseBackground from "@/components/NoiseBackground";
import { Navbar } from "@/layouts/Navbar";
import MainLayout from "@/layouts/MainLayout";
import Footer from "@/layouts/Footer";

const outfit = Outfit({
  weight: ["100", "200", "300", "400", "600", "700", "800", "900"],
  subsets: ["latin"],
  style: ["normal"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} bg-[#151312]`}>
        <NoiseBackground className="relative z-10 container pt-6">
          <Navbar />
          <MainLayout>{children}</MainLayout>
          <Footer />
        </NoiseBackground>
      </body>
    </html>
  );
}
